"""Pure data models for the wargame. No simulation logic lives here."""

from axis.domain.coordinates import BoundingBox, Coordinate
from axis.domain.country import (
    BilateralRelation,
    Border,
    CabinetMember,
    Composition,
    Country,
    Demographics,
    Diplomacy,
    EnergyLogistics,
    Geography,
    Government,
    InventoryLine,
    InventoryStatus,
    KeyBase,
    Military,
    MilitaryPosture,
    NuclearPosture,
    NuclearStatus,
    PublicOpinion,
    RegimeType,
    RelationStatus,
    ServiceBranch,
    Treaty,
)
from axis.domain.faction import Allegiance, Faction
from axis.domain.city import City, CityImportance
from axis.domain.frontline import Frontline
from axis.domain.military_assets import (
    Airfield,
    AreaOfResponsibility,
    AssetKind,
    BorderCrossing,
    CrossingMode,
    Depot,
    IsrCoverage,
    MissileRange,
    NavalBase,
    SupplyLine,
)
from axis.domain.oblast import Oblast
from axis.domain.political import (
    CredibilityTrack,
    FactionPressure,
    GapEvent,
    LeaderSignal,
    LeaderSignalType,
    PressureState,
    RegionPressure,
)
from axis.domain.territory import Territory
from axis.domain.theater import Theater

__all__ = [
    "Airfield",
    "Allegiance",
    "AreaOfResponsibility",
    "AssetKind",
    "BilateralRelation",
    "Border",
    "BorderCrossing",
    "BoundingBox",
    "CabinetMember",
    "City",
    "CityImportance",
    "Composition",
    "Coordinate",
    "Country",
    "CredibilityTrack",
    "CrossingMode",
    "Demographics",
    "Depot",
    "Diplomacy",
    "EnergyLogistics",
    "Faction",
    "FactionPressure",
    "Frontline",
    "GapEvent",
    "Geography",
    "Government",
    "InventoryLine",
    "InventoryStatus",
    "IsrCoverage",
    "KeyBase",
    "LeaderSignal",
    "LeaderSignalType",
    "Military",
    "MilitaryPosture",
    "MissileRange",
    "NavalBase",
    "NuclearPosture",
    "NuclearStatus",
    "Oblast",
    "PressureState",
    "PublicOpinion",
    "RegionPressure",
    "RegimeType",
    "RelationStatus",
    "ServiceBranch",
    "SupplyLine",
    "Territory",
    "Theater",
    "Treaty",
]
